# Global Costmap Fusion Node Configuration
# GlobalCostmapFusion Configuration

global_costmap_fusion:
  ros__parameters:
    robots: ["robot1", "robot2", "robot3", "robot4", "robot5", "robot6"]
    robot_radius: 0.3          # Radius of each robot in meters
    exclusion_buffer: 0.5      # Additional buffer around robots to exclude from obstacle detection
    
    # Update frequencies
    update_frequency: 10.0     # Hz - How often to publish shared obstacles grid
    robot_timeout: 5.0         # Seconds - Time before marking robot as inactive
    
    # Frame and topic configuration
    global_frame: "map"        # Global reference frame
    output_topic: /shared_obstacles_grid  # Topic to publish shared obstacles
    scan_topic: scan        # Laser scan topic suffix (will be /<robot_id>/scan)
    
    # Grid configuration
    grid_resolution: 0.05      # meters per pixel
    grid_width: 100.0          # meters - total width of occupancy grid
    grid_height: 100.0         # meters - total height of occupancy grid


#======================================================================
# Example configuration for one robot
# This configuration is not functional and is only an example, 
# Copy-Paste the following block in your config file and check that 
# The namespacing is correct
#======================================================================


# planner_server:
#   ros__parameters:
#     expected_planner_frequency: 20.0
#     use_sim_time: True
#     planner_plugins: ["GridBased"]
#     GridBased:
#       plugin: "nav2_navfn_planner/NavfnPlanner"
#       tolerance: 0.5
#       use_astar: false
#       allow_unknown: true

#     global_costmap:
#       global_costmap:
#         ros__parameters:
#           update_frequency: 1.0
#           publish_frequency: 1.0
#           global_frame: map
#           robot_base_frame: robot1/base_link
#           use_sim_time: True
#           robot_radius: 0.35
#           resolution: 0.05
#           track_unknown_space: true
#           plugins: ["static_layer", "multi_robot_layer", "inflation_layer"]
          
#           static_layer:
#             plugin: "nav2_costmap_2d/StaticLayer"
#             map_subscribe_transient_local: True
            
#           multi_robot_layer:
#             plugin: "multi_robot_costmap_plugin::MultiRobotLayer"
#             enabled: True
#             update_topic: "/shared_costmap_updates"
#             robot_namespace: "robot1"
#             robot_radius: 0.35
#             exclusion_buffer: 0.5
#             max_update_age: 5.0
            
#           inflation_layer:
#             plugin: "nav2_costmap_2d/InflationLayer"
#             cost_scaling_factor: 3.0
#             inflation_radius: 0.55